version: "3"

services:

  backend-db:
    
    image: env-db
   
    depends_on:
      - mongodb
   
    environment: 
      dynamodb_region_name : "us-east-1"
      dynamodb_table : "grammar-data"
      origins : "*"
      database : "mongodb"
      mongodbIp : "mongodb"
      mongodbPort : 27017
      # database='dynamodb'
      AWS_SERVER_PUBLIC_KEY : ""
      AWS_SERVER_SECRET_KEY : ""

  backend-ml:
    

    image: gec_ml:2
    

  mongodb:
    
    image: mongo
    ports:
      - "27017:27017"
    
    volumes:  #要刪掉
      - ./mongo/import.sh:/import.sh
      - ./mongo/grammar-data.csv:/tmp/grammar-data.csv
  
  mongo_seed:
    image: mongo

    volumes:
      - ./mongo/import.sh:/import.sh
      - ./mongo/grammar-data.csv:/tmp/grammar-data.csv
    command:
      ["sh","import.sh"]
    depends_on:
      - mongodb
    

  nginx:
    

    ports:
      - "80:80"
   
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw,file



